### ISSUE TITLE
delete-branch not doing anything

### ISSUE THREAD

**Issue by jordansexton** [tj/git-extras#720]
`git delete-branch` / `git-delete-branch` does nothing to local or remote branches for me. Other git extras commands (e.g. `undo`, `info`) work.

#### Versions & Paths
```shell
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202
➜  ~ brew list | grep git
git
git-extras
➜  ~ git --version
git version 2.17.1
➜  ~ git extras --version
4.5.0
➜  ~ which git-extras
/usr/local/bin/git-extras
➜  ~ which git-delete-branch
/usr/local/bin/git-delete-branch
```

#### Reproduction
```shell
➜  ~ mkdir git-extras-testing
➜  ~ cd git-extras-testing
➜  git-extras-testing git init
Initialized empty Git repository in /Users/jordan/git-extras-testing/.git/
➜  git-extras-testing git:(master) touch README.md
➜  git-extras-testing git:(master) ✗ git add .
➜  git-extras-testing git:(master) ✗ git commit -m "init"
[master (root-commit) a635f40] init
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.md
➜  git-extras-testing git:(master) git checkout -b branch-to-delete
Switched to a new branch 'branch-to-delete'
➜  git-extras-testing git:(branch-to-delete) git checkout master
Switched to branch 'master'
➜  git-extras-testing git:(master) git delete-branch branch-to-delete
➜  git-extras-testing git:(master) git branch
  branch-to-delete
* master
➜  git-extras-testing git:(master) git branch -D branch-to-delete
Deleted branch branch-to-delete (was a635f40).
```

**Comment by spacewander** [comment]
@jordansexton 
Maybe it is fixed in https://github.com/tj/git-extras/pull/706?
Could you install git-extras from the source of master branch to verify it?

**Comment by carlosagp** [comment]
@spacewander I have the same symptom. I installed from source and branches are still not deleted. 
```
$ git --version
git version 2.15.1 (Apple Git-101)
$ git extras --version
4.5.0
$ which git-extras
/usr/local/bin/git-extras
$ which git-delete-branch
/usr/local/bin/git-delete-branch
$ git branch
* master
  needs_to_go_away
$ git delete-branch needs_to_go_away
$  git branch                                                                                                                                                                                                                
* master
  needs_to_go_away
```

**Comment by spacewander** [comment]
@carlosagp 
Could you install the git-extras from master branch (version `4.6.0-dev`) and verify if the bug is fixed?
It may be a known bug fixed after version `4.5.0`.

**Comment by jordansexton** [comment]
@spacewander I installed from source, and it looks like it is fixed in master. Thanks!

**Comment by jordansexton** [comment]
@carlosagp
I followed instructions on https://github.com/tj/git-extras/blob/master/Installation.md#building-from-source and got it working. I ran `brew uninstall git-extras` first to avoid potential conflict. You'll want to skip the

```shell
git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
```

command and just `make install` from master though. You can verify it's running the right version afterward with

```shell
➜  ~ git extras --version
4.6.0-dev
```
